// this file 参考了 https://github.com/meganz/webclient/blob/master/js/filetypes.js
export const ext: { [key: string]: string[] } = {
  "3ds": ["threed", "20238"],
  "3dm": ["threed", "20239"],
  max: ["threed", "20305"],
  obj: ["threed", "20315"],
  aep: ["aftereffects", "20244"],
  aet: ["aftereffects", "20378"],
  mp3: ["audio", "20310"],
  wav: ["audio", "20354"],
  "3ga": ["audio", "Audio"],
  aif: ["audio", "20246"],
  aiff: ["audio", "20246"],
  flac: ["audio", "20280"],
  iff: ["audio", "20292"],
  m4a: ["audio", "20304"],
  wma: ["audio", "20357"],
  dxf: ["cad", "20276"],
  dwg: ["cad", "20274"],
  zip: ["compressed", "20364"],
  rar: ["compressed", "20332"],
  tgz: ["compressed", "20386"],
  gz: ["compressed", "20288"],
  bz2: ["compressed", "20259"],
  tbz: ["compressed", "20346"],
  tar: ["compressed", "16689"],
  "7z": ["compressed", "20242"],
  sitx: ["compressed", "20338"],
  dmg: ["dmg", "20271"],
  xls: ["excel", "20362"],
  xlsx: ["excel", "20389"],
  xlt: ["excel", "20390"],
  xltm: ["excel", "20391"],
  exe: ["executable", "20278"],
  com: ["executable", "20265"],
  bin: ["executable", "Executable"],
  apk: ["executable", "1890"],
  app: ["executable", "20248"],
  msi: ["executable", "20312"],
  cmd: ["executable", "Executable"],
  gadget: ["executable", "20284"],
  fnt: ["font", "20282"],
  otf: ["font", "20317"],
  ttf: ["font", "20351"],
  fon: ["font", "20283"],
  "*": ["generic", "File"],
  ai: ["illustrator", "20245"],
  ait: ["illustrator", "20379"],
  gif: ["image", "20285"],
  tiff: ["image", "20349"],
  tif: ["image", "20348"],
  bmp: ["image", "20258"],
  png: ["image", "20325"],
  tga: ["image", "20347"],
  jpg: ["image", "20298"],
  jpeg: ["image", "20298"],
  heic: ["image", "20290"],
  webp: ["image", "20356"],
  avif: ["image", "23431"],
  indd: ["indesign", "20294"],
  key: ["keynote", "20300"],
  numbers: ["numbers", "20314"],
  sxw: ["openoffice", "20374"],
  stw: ["openoffice", "20369"],
  sxc: ["openoffice", "20370"],
  stc: ["openoffice", "20343"],
  sxi: ["openoffice", "20372"],
  sti: ["raw", "20368"],
  sxd: ["openoffice", "20371"],
  std: ["openoffice", "20367"],
  sxm: ["openoffice", "20373"],
  pages: ["pages", "20318"],
  pdf: ["pdf", "20320"],
  abr: ["photoshop", "Adobe Photoshop"],
  psb: ["photoshop", "20329"],
  psd: ["photoshop", "20383"],
  pps: ["powerpoint", "20327"],
  ppt: ["powerpoint", "20327"],
  pptx: ["powerpoint", "20327"],
  prproj: ["premiere", "20326"],
  ppj: ["premiere", "20326"],
  "3fr": ["raw", "20240"],
  ari: ["raw", "20240"],
  arq: ["raw", "20240"],
  arw: ["raw", "20240"],
  bay: ["raw", "20257"],
  bmq: ["raw", "20240"],
  cap: ["raw", "20240"],
  cine: ["raw", "20240"],
  cr2: ["raw", "20266"],
  cr3: ["raw", "20240"],
  crw: ["raw", "20240"],
  ciff: ["raw", "20240"],
  cs1: ["raw", "20240"],
  dc2: ["raw", "20240"],
  dcr: ["raw", "20240"],
  dsc: ["raw", "20240"],
  dng: ["raw", "20270"],
  drf: ["raw", "20240"],
  eip: ["raw", "20240"],
  erf: ["raw", "20240"],
  fff: ["raw", "20240"],
  ia: ["raw", "20240"],
  iiq: ["raw", "20240"],
  k25: ["raw", "20240"],
  kc2: ["raw", "20240"],
  kdc: ["raw", "20240"],
  mdc: ["raw", "20240"],
  mef: ["raw", "20240"],
  mos: ["raw", "20240"],
  mrw: ["raw", "20266"],
  nef: ["raw", "20240"],
  nrw: ["raw", "20240"],
  obm: ["raw", "20240"],
  orf: ["raw", "20240"],
  ori: ["raw", "20240"],
  pef: ["raw", "20240"],
  ptx: ["raw", "20240"],
  pxn: ["raw", "20240"],
  qtk: ["raw", "20240"],
  raf: ["raw", "20240"],
  raw: ["raw", "20240"],
  rdc: ["raw", "20240"],
  rw2: ["raw", "20335"],
  rwl: ["raw", "20240"],
  rwz: ["raw", "20240"],
  sr2: ["raw", "20240"],
  srf: ["raw", "20341"],
  srw: ["raw", "20240"],
  x3f: ["raw", "20240"],
  sketch: ["sketch", "20340"],
  ods: ["spreadsheet", "20370"],
  ots: ["spreadsheet", "20382"],
  gsheet: ["spreadsheet", "20287"],
  nb: ["spreadsheet", "20313"],
  xlr: ["spreadsheet", "20388"],
  torrent: ["torrent", "20350"],
  txt: ["text", "20387"],
  ans: ["text", "20247"],
  ascii: ["text", "20251"],
  log: ["text", "20302"],
  wpd: ["text", "20359"],
  json: ["text", "Text"],
  md: ["text", "Text"],
  svgz: ["vector", "20385"],
  svg: ["vector", "20344"],
  cdr: ["vector", "20262"],
  eps: ["vector", "20277"],
  mkv: ["video", "20308"],
  webm: ["video", "20355"],
  avi: ["video", "20255"],
  mp4: ["video", "20365"],
  m4v: ["video", "Video"],
  mpg: ["video", "20311"],
  mpeg: ["video", "20311"],
  mov: ["video", "20309"],
  "3g2": ["video", "20241"],
  "3gp": ["video", "20375"],
  asf: ["video", "20252"],
  wmv: ["video", "20358"],
  vob: ["video", "20353"],
  html: ["web-data", "20291"],
  xml: ["web-data", "20363"],
  shtml: ["web-data", "20337"],
  dhtml: ["web-data", "20268"],
  js: ["web-data", "20299"],
  css: ["web-data", "20267"],
  jar: ["web-data", "20296"],
  java: ["web-data", "20297"],
  class: ["web-data", "20264"],
  php: ["web-lang", "20321"],
  php3: ["web-lang", "20321"],
  php4: ["web-lang", "20321"],
  php5: ["web-lang", "20321"],
  phtml: ["web-lang", "20322"],
  inc: ["web-lang", "20293"],
  asp: ["web-lang", "20253"],
  pl: ["web-lang", "20323"],
  cgi: ["web-lang", "20263"],
  py: ["web-lang", "20330"],
  sql: ["web-lang", "20339"],
  accdb: ["web-lang", "20243"],
  db: ["web-lang", "20376"],
  dbf: ["web-lang", "20376"],
  mdb: ["web-lang", "20306"],
  pdb: ["web-lang", "20377"],
  c: ["web-lang", "20260"],
  cpp: ["web-lang", "20261"],
  h: ["web-lang", "20289"],
  cs: ["web-lang", "Web Server Code"],
  sh: ["web-lang", "20336"],
  vb: ["web-lang", "22676"],
  swift: ["web-lang", "22677"],
  doc: ["word", "20272"],
  docx: ["word", "20381"],
  dotx: ["word", "20273"],
  wps: ["word", "20360"],
  odt: ["word", "20316"],
  rtf: ["word", "20334"],
};
var extmime: { [key: string]: string } = {
  "3ds": "image/x-3ds",
  "3g2": "video/3gpp2",
  "3gp": "video/3gpp",
  "7z": "application/x-7z-compressed",
  aac: "audio/x-aac",
  abw: "application/x-abiword",
  ace: "application/x-ace-compressed",
  adp: "audio/adpcm",
  aif: "audio/x-aiff",
  aifc: "audio/x-aiff",
  aiff: "audio/x-aiff",
  apk: "application/vnd.android.package-archive",
  asf: "video/x-ms-asf",
  asx: "video/x-ms-asf",
  atom: "application/atom+xml",
  au: "audio/basic",
  avi: "video/x-msvideo",
  avif: "image/avif",
  bat: "application/x-msdownload",
  bmp: "image/bmp",
  btif: "image/prs.btif",
  bz: "application/x-bzip",
  bz2: "application/x-bzip2",
  caf: "audio/x-caf",
  cgm: "image/cgm",
  cmx: "image/x-cmx",
  com: "application/x-msdownload",
  conf: "text/plain",
  css: "text/css",
  csv: "text/csv",
  dbk: "application/docbook+xml",
  deb: "application/x-debian-package",
  def: "text/plain",
  djv: "image/vnd.djvu",
  djvu: "image/vnd.djvu",
  dll: "application/x-msdownload",
  dmg: "application/x-apple-diskimage",
  doc: "application/msword",
  docm: "application/vnd.ms-word.document.macroenabled.12",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  dot: "application/msword",
  dotm: "application/vnd.ms-word.template.macroenabled.12",
  dotx: "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
  dra: "audio/vnd.dra",
  dtd: "application/xml-dtd",
  dts: "audio/vnd.dts",
  dtshd: "audio/vnd.dts.hd",
  dvb: "video/vnd.dvb.file",
  dwg: "image/vnd.dwg",
  dxf: "image/vnd.dxf",
  ecelp4800: "audio/vnd.nuera.ecelp4800",
  ecelp7470: "audio/vnd.nuera.ecelp7470",
  ecelp9600: "audio/vnd.nuera.ecelp9600",
  emf: "application/x-msmetafile",
  emz: "application/x-msmetafile",
  eol: "audio/vnd.digital-winds",
  epub: "application/epub+zip",
  exe: "application/x-msdownload",
  f4v: "video/x-f4v",
  fbs: "image/vnd.fastbidsheet",
  fh: "image/x-freehand",
  fh4: "image/x-freehand",
  fh5: "image/x-freehand",
  fh7: "image/x-freehand",
  fhc: "image/x-freehand",
  flac: "audio/x-flac",
  fli: "video/x-fli",
  flv: "video/x-flv",
  fpx: "image/vnd.fpx",
  fst: "image/vnd.fst",
  fvt: "video/vnd.fvt",
  g3: "image/g3fax",
  gif: "image/gif",
  h261: "video/h261",
  h263: "video/h263",
  h264: "video/h264",
  heif: "image/heif",
  heic: "image/heic",
  htm: "text/html",
  html: "text/html",
  ico: "image/x-icon",
  ief: "image/ief",
  iso: "application/x-iso9660-image",
  jpe: "image/jpeg",
  jpeg: "image/jpeg",
  jpg: "image/jpeg",
  jpgm: "video/jpm",
  jpgv: "video/jpeg",
  jpm: "video/jpm",
  json: "application/json",
  jsonml: "application/jsonml+json",
  kar: "audio/midi",
  ktx: "image/ktx",
  list: "text/plain",
  log: "text/plain",
  lvp: "audio/vnd.lucent.voice",
  m13: "application/x-msmediaview",
  m14: "application/x-msmediaview",
  m1v: "video/mpeg",
  m21: "application/mp21",
  m2a: "audio/mpeg",
  m2v: "video/mpeg",
  m3a: "audio/mpeg",
  m3u: "audio/x-mpegurl",
  m3u8: "application/vnd.apple.mpegurl",
  m4a: "audio/mp4",
  m4u: "video/vnd.mpegurl",
  m4v: "video/x-m4v",
  mdi: "image/vnd.ms-modi",
  mid: "audio/midi",
  midi: "audio/midi",
  mj2: "video/mj2",
  mjp2: "video/mj2",
  mk3d: "video/x-matroska",
  mka: "audio/x-matroska",
  mks: "video/x-matroska",
  mkv: "video/x-matroska",
  mmr: "image/vnd.fujixerox.edmics-mmr",
  mng: "video/x-mng",
  mov: "video/quicktime",
  movie: "video/x-sgi-movie",
  mp2: "audio/mpeg",
  mp21: "application/mp21",
  mp2a: "audio/mpeg",
  mp3: "audio/mpeg",
  mp4: "video/mp4",
  mp4a: "audio/mp4",
  mp4s: "application/mp4",
  mp4v: "video/mp4",
  mpe: "video/mpeg",
  mpeg: "video/mpeg",
  mpg: "video/mpeg",
  mpg4: "video/mp4",
  mpga: "audio/mpeg",
  mpkg: "application/vnd.apple.installer+xml",
  msi: "application/x-msdownload",
  mvb: "application/x-msmediaview",
  mxf: "application/mxf",
  mxml: "application/xv+xml",
  mxu: "video/vnd.mpegurl",
  npx: "image/vnd.net-fpx",
  odb: "application/vnd.oasis.opendocument.database",
  odc: "application/vnd.oasis.opendocument.chart",
  odf: "application/vnd.oasis.opendocument.formula",
  odft: "application/vnd.oasis.opendocument.formula-template",
  odg: "application/vnd.oasis.opendocument.graphics",
  odi: "application/vnd.oasis.opendocument.image",
  odm: "application/vnd.oasis.opendocument.text-master",
  odp: "application/vnd.oasis.opendocument.presentation",
  ods: "application/vnd.oasis.opendocument.spreadsheet",
  odt: "application/vnd.oasis.opendocument.text",
  oga: "audio/ogg",
  ogg: "audio/ogg",
  ogv: "video/ogg",
  ogx: "application/ogg",
  otc: "application/vnd.oasis.opendocument.chart-template",
  otg: "application/vnd.oasis.opendocument.graphics-template",
  oth: "application/vnd.oasis.opendocument.text-web",
  oti: "application/vnd.oasis.opendocument.image-template",
  otp: "application/vnd.oasis.opendocument.presentation-template",
  ots: "application/vnd.oasis.opendocument.spreadsheet-template",
  ott: "application/vnd.oasis.opendocument.text-template",
  oxt: "application/vnd.openofficeorg.extension",
  pbm: "image/x-portable-bitmap",
  pct: "image/x-pict",
  pcx: "image/x-pcx",
  pdf: "application/pdf",
  pgm: "image/x-portable-graymap",
  pic: "image/x-pict",
  plb: "application/vnd.3gpp.pic-bw-large",
  png: "image/png",
  pnm: "image/x-portable-anymap",
  pot: "application/vnd.ms-powerpoint",
  potx: "application/vnd.openxmlformats-officedocument.presentationml.template",
  ppm: "image/x-portable-pixmap",
  pps: "application/vnd.ms-powerpoint",
  ppsx: "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  psb: "application/vnd.3gpp.pic-bw-small",
  psd: "image/vnd.adobe.photoshop",
  pvb: "application/vnd.3gpp.pic-bw-var",
  pya: "audio/vnd.ms-playready.media.pya",
  pyv: "video/vnd.ms-playready.media.pyv",
  qt: "video/quicktime",
  ra: "audio/x-pn-realaudio",
  ram: "audio/x-pn-realaudio",
  ras: "image/x-cmu-raster",
  rgb: "image/x-rgb",
  rip: "audio/vnd.rip",
  rlc: "image/vnd.fujixerox.edmics-rlc",
  rmi: "audio/midi",
  rmp: "audio/x-pn-realaudio-plugin",
  s3m: "audio/s3m",
  sgi: "image/sgi",
  sgm: "text/sgml",
  sgml: "text/sgml",
  sid: "image/x-mrsid-image",
  sil: "audio/silk",
  sldx: "application/vnd.openxmlformats-officedocument.presentationml.slide",
  smv: "video/x-smv",
  snd: "audio/basic",
  spx: "audio/ogg",
  srt: "application/x-subrip",
  sub: "text/vnd.dvb.subtitle",
  svg: "image/svg+xml",
  svgz: "image/svg+xml",
  swf: "application/x-shockwave-flash",
  tcap: "application/vnd.3gpp2.tcap",
  text: "text/plain",
  tga: "image/x-tga",
  tif: "image/tiff",
  tiff: "image/tiff",
  torrent: "application/x-bittorrent",
  tsv: "text/tab-separated-values",
  ttl: "text/turtle",
  txt: "text/plain",
  udeb: "application/x-debian-package",
  uva: "audio/vnd.dece.audio",
  uvg: "image/vnd.dece.graphic",
  uvh: "video/vnd.dece.hd",
  uvi: "image/vnd.dece.graphic",
  uvm: "video/vnd.dece.mobile",
  uvp: "video/vnd.dece.pd",
  uvs: "video/vnd.dece.sd",
  uvu: "video/vnd.uvvu.mp4",
  uvv: "video/vnd.dece.video",
  uvva: "audio/vnd.dece.audio",
  uvvg: "image/vnd.dece.graphic",
  uvvh: "video/vnd.dece.hd",
  uvvi: "image/vnd.dece.graphic",
  uvvm: "video/vnd.dece.mobile",
  uvvp: "video/vnd.dece.pd",
  uvvs: "video/vnd.dece.sd",
  uvvu: "video/vnd.uvvu.mp4",
  uvvv: "video/vnd.dece.video",
  viv: "video/vnd.vivo",
  vob: "video/x-ms-vob",
  wav: "audio/x-wav",
  wax: "audio/x-ms-wax",
  wbmp: "image/vnd.wap.wbmp",
  wdp: "image/vnd.ms-photo",
  weba: "audio/webm",
  webm: "video/webm",
  webp: "image/webp",
  wm: "video/x-ms-wm",
  wma: "audio/x-ms-wma",
  wmf: "application/x-msmetafile",
  wmv: "video/x-ms-wmv",
  wmx: "video/x-ms-wmx",
  wvx: "video/x-ms-wvx",
  xap: "application/x-silverlight-app",
  xbm: "image/x-xbitmap",
  xht: "application/xhtml+xml",
  xhtml: "application/xhtml+xml",
  xhvml: "application/xv+xml",
  xif: "image/vnd.xiff",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xltx: "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
  xm: "audio/xm",
  xml: "application/xml",
  xop: "application/xop+xml",
  xpl: "application/xproc+xml",
  xpm: "image/x-xpixmap",
  xsl: "application/xml",
  xslt: "application/xslt+xml",
  xspf: "application/xspf+xml",
  xvm: "application/xv+xml",
  xvml: "application/xv+xml",
  xwd: "image/x-xwindowdump",
  zip: "application/zip",

  // RAW Images
  "3fr": "image/x-hasselblad-3fr",
  ari: "image/z-arrialexa-ari",
  arw: "image/x-sony-arw",
  arq: "image/x-sony-arq",
  bay: "image/x-casio-bay",
  bmq: "image/x-nucore-bmq",
  cap: "image/x-phaseone-cap",
  cr2: "image/x-canon-cr2",
  cr3: "image/x-canon-cr3",
  crw: "image/x-canon-crw",
  cs1: "image/x-sinar-cs1",
  dc2: "image/x-kodak-dc2",
  dcr: "image/x-kodak-dcr",
  dng: "image/x-dcraw",
  dsc: "image/x-kodak-dsc",
  drf: "image/x-kodak-drf",
  erf: "image/x-epson-erf",
  eip: "image/x-phaseone-eip",
  fff: "image/x-hasselblad-fff",
  iiq: "image/x-phaseone-iiq",
  k25: "image/x-kodak-k25",
  kc2: "image/x-kodak-kc2",
  kdc: "image/x-kodak-kdc",
  mdc: "image/x-monolta-mdc",
  mef: "image/x-mamiya-mef",
  mos: "image/x-leaf-mos",
  mrw: "image/x-minolta-mrw",
  nef: "image/x-nikon-nef",
  nrw: "image/x-nikon-nrw",
  obm: "image/x-olympus-obm",
  orf: "image/x-olympus-orf",
  ori: "image/x-olympus-ori",
  pef: "image/x-pentax-pef",
  ptx: "image/x-pentax-ptx",
  pxn: "image/x-logitech-pxn",
  qtk: "image/x-apple-qtx",
  raf: "image/x-fuji-raf",
  raw: "image/x-panasonic-raw",
  rdc: "image/x-difoma-rdc",
  rw2: "image/x-panasonic-rw2",
  rwz: "image/x-rawzor-rwz",
  rwl: "image/x-leica-rwl",
  sr2: "image/x-sony-sr2",
  srf: "image/x-sony-srf",
  srw: "image/x-samsung-srw",
  sti: "image/x-sinar-sti",
  x3f: "image/x-sigma-x3f",
  ciff: "image/x-canon-crw",
  cine: "image/x-phantom-cine",
  ia: "image/x-sinar-ia",

  // Uncommon Images
  aces: "image/aces",
  avci: "image/avci",
  avcs: "image/avcs",
  fits: "image/fits",
  g3fax: "image/g3fax",
  hej2k: "image/hej2k",
  hsj2: "image/hsj2",
  jls: "image/jls",
  jp2: "image/jp2",
  jph: "image/jph",
  jphc: "image/jphc",
  jpx: "image/jpx",
  jxr: "image/jxr",
  jxrA: "image/jxrA",
  jxrS: "image/jxrS",
  jxs: "image/jxs",
  jxsc: "image/jxsc",
  jxsi: "image/jxsi",
  jxss: "image/jxss",
  naplps: "image/naplps",
  pti: "image/prs.pti",
  t38: "image/t38",
};
/** 获取文件类型具体描述 */
export const getMeagaFilemime = (fileName: string, def: string) => {
  var fext = getFileextByFileName(fileName);
  return extmime[fext] || def || "application/octet-stream";
};
/** 获取文件类型 */
export const getMeagaFiletype = (
  fileName: string,
  // getFullType?: boolean,
  ik?: boolean
) => {
  "use strict";
  var name = fileName;
  var fext = getFileextByFileName(name, false, ik);

  if (ext[fext]) {
    // if (getFullType) {
    //   return ext[fext];
    // }
    // return ext[fext][1];
    return ext[fext][0];
  }
  return "generic";
  // return "18055"; // 'File' 默认的文件名
  // return fext.length ? l[20366].replace("%1", fext.toUpperCase()) : l[18055];
};
/** 获取文件类型icon */
export const getMeagaFileIcon = (fileName: string) => {
  "use strict";
  let icon: string;

  // if (node.t) {
  //   // if (
  //   //   node.t & M.IS_SHARED ||
  //   //   M.ps[node.h] ||
  //   //   M.getNodeShareUsers(node, "EXP").length
  //   // ) {
  //   //   icon = "folder-shared";

  //   //   if ((window as any).__isMobile__) {
  //   //     icon = "outgoing-share-folder";
  //   //   }
  //   // } else {
  //   //   icon = "folder";
  //   // }
  //   icon = "folder";
  // } else if (ext[getFileextByFileName(fileName)]) {
  //   icon = ext[getFileextByFileName(fileName)][0];
  // } else {
  //   icon = "generic";
  // }
  if (ext[getFileextByFileName(fileName)]) {
    icon = ext[getFileextByFileName(fileName)][0];
  } else {
    icon = "generic";
  }

  return icon;
};
/** 根据文件名称返回扩展名 */
export const getFileextByFileName = (
  name: string, // 文件名
  upper?: boolean, // 是否大写
  iknowwhatimdoing?: boolean // 强行裁剪?
) => {
  "use strict";

  name = String(name || "");
  if (!name) {
    name = "unknown";
  }

  var ext = name.substr(name.lastIndexOf(".") + 1);
  if (ext === name) {
    ext = "";
  } else if (!iknowwhatimdoing) {
    ext = ext.replace(/<[^>]*>/g, "").replace(/[^\w+]/g, "");

    if (ext.length > 9) {
      ext = ext.substr(0, 9);
    }
  }

  return upper ? ext.toUpperCase() : ext.toLowerCase();
};
